language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install pipenv
  - pipenv install --dev --three

before_script: pipenv run flake8
script: pipenv run pytest
